on:
  push:
    branches:
    - main
    - release/*
jobs:  
  sendmail:
    runs-on: ubuntu

    steps:
      - uses: devellany/send-mailer@v1.0.2
        with:      
         host: smtp.google.com
         account: ${{secrets.ACCOUNT}}
         password: ${{secrets.MAIL_PASSWORD}}
         sender: devellany
         from: examencloudsystemen.malikgv@gmail.com
         to: examencloudsystemen.malikgv@gmail.com
         subject: text
         body: text
         contentType: text/html
         attachments: file://tmp/linesofcode.txt
